rrs_upstream_email.py: fix email sending error
According to commit [1], use recipesymbol instead of recipe to fix email
sending errors:

django.core.exceptions.FieldError: Cannot resolve keyword 'recipe' into
field. Choices are: history, history_id, id, maintainer, maintainer_id,
recipesymbol, recipesymbol_id

[1] https://git.yoctoproject.org/layerindex-web/commit/?id=c0b84391827840ef302b1172f7533e887af50a54

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Tim Orling <tim.orling@konsulko.com>