rrs_upstream_history: allow skip update_data
Fixes:
Traceback (most recent call last):
  File "/opt/layerindex/./rrs/tools/rrs_upstream_history.py", line 210, in <module>
    set_regexes(recipe_data)
  File "/opt/layerindex/./rrs/tools/rrs_upstream_history.py", line 73, in set_regexes
    bb.data.update_data(localdata)
AttributeError: module 'bb.data' has no attribute 'update_data'

bb.data.update_data was dropped in:
584989ed 'data/data_smart/build: Clean up datastore finalize/update_data references'

While we are here, drop some trailing whitespace.

Signed-off-by: Tim Orling <tim.orling@konsulko.com>